export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: "/api/auth/register",
    LOGIN: "/api/auth/login",
    LOGOUT: "/api/auth/logout",
    FORGOT_PASSWORD: "/api/auth/forgot-password",
    RESET_PASSWORD: "/api/auth/reset-password",
    VERIFY_EMAIL: "/api/auth/verify-email",
    ME: "/api/auth/me",
    REFRESH_TOKEN: "/api/auth/refresh-token",
  },
  USER: {
    PROFILE: "/api/user/profile",
    CHANGE_PASSWORD: "/api/user/change-password",
    API_KEY: "/api/user/api-key",
    REGENERATE_API_KEY: "/api/user/api-key/regenerate",
  },
  SERVICES: {
    LIST: "/api/services",
    CATEGORIES: "/api/services/categories",
    DETAIL: (id: string | number) => `/api/services/${id}`,
  },
  ORDERS: {
    CREATE: "/api/orders",
    LIST: "/api/orders",
    DETAIL: (id: string | number) => `/api/orders/${id}`,
    CANCEL: (id: string | number) => `/api/orders/${id}/cancel`,
    REFILL: (id: string | number) => `/api/orders/${id}/refill`,
  },
  WALLET: {
    BALANCE: "/api/wallet/balance",
    TRANSACTIONS: "/api/wallet/transactions",
    ADD_FUNDS: "/api/wallet/add-funds",
    VERIFY_PAYMENT: "/api/wallet/verify-payment",
  },
  SUPPORT: {
    LIST: "/api/tickets",
    CREATE: "/api/tickets",
    DETAIL: (id: string | number) => `/api/tickets/${id}`,
    REPLY: (id: string | number) => `/api/tickets/${id}/reply`,
    CLOSE: (id: string | number) => `/api/tickets/${id}/close`,
  },
  AFFILIATE: {
    STATS: "/api/affiliate/stats",
    REFERRALS: "/api/affiliate/referrals",
    WITHDRAW: "/api/affiliate/withdraw",
  },
  ADMIN: {
    STATS: "/api/admin/stats",
    USERS: "/api/admin/users",
    USER_DETAIL: (id: string | number) => `/api/admin/users/${id}`,
    ORDERS: "/api/admin/orders",
    SERVICES: "/api/admin/services",
    CATEGORIES: "/api/admin/categories",
    PAYMENTS: "/api/admin/payments",
    SETTINGS: "/api/admin/settings",
    TICKETS: "/api/admin/tickets",
  },
  PUBLIC_API: {
    SERVICES: "/api/v1/services",
    ORDER: "/api/v1/order",
    STATUS: "/api/v1/status",
    BALANCE: "/api/v1/balance",
  },
} as const;
