export const STRINGS = {
  APP: {
    NAME: "Virtue",
    LOGO: "Virtue",
    TAGLINE: "Grow Your Social Presence Instantly",
    CURRENCY_SYMBOL: "₹",
  },
  LANDING: {
    HERO_TITLE: "Boost Your Social Media Presence Today",
    HERO_SUBTITLE: "Get real followers, likes, views, and shares across all platforms. Fast delivery, cheap rates, and 24/7 client support.",
    CTA_GET_STARTED: "Get Started",
    CTA_DEMO: "Watch Demo",
    CTA_SERVICES: "View Services",
    STATS_ORDERS: "Total Orders",
    STATS_USERS: "Happy Users",
    STATS_SERVICES: "Active Services",
    STATS_UPTIME: "Uptime Guaranteed",
    HOW_IT_WORKS: "How It Works",
    HOW_IT_WORKS_SUBTITLE: "Three simple steps to accelerate your social media growth",
    HOW_STEP_1_TITLE: "Create Account",
    HOW_STEP_1_DESC: "Register a free account on our platform quickly and securely in seconds.",
    HOW_STEP_2_TITLE: "Select Service",
    HOW_STEP_2_DESC: "Browse and select from our high-quality Instagram and YouTube marketing services.",
    HOW_STEP_3_TITLE: "Checkout Securely",
    HOW_STEP_3_DESC: "Place your order and pay instantly and securely using live Razorpay payments.",
    HOW_STEP_4_TITLE: "See Growth",
    HOW_STEP_4_DESC: "Watch your social channels grow with fast delivery and high retention.",
    PLATFORMS_TITLE: "Supported Platforms",
    PLATFORMS_SUBTITLE: "We cater services for every major social network available",
    SERVICES_PREVIEW_TITLE: "Popular Services Pricing",
    SERVICES_PREVIEW_SUBTITLE: "Check out a small selection of our best-selling high-speed services",
    FEATURES_TITLE: "Why Choose Us?",
    FEATURES_SUBTITLE: "We are committed to providing the ultimate social marketing tools and panels",
    FEAT_DELIVERY_TITLE: "Lightning Fast Delivery",
    FEAT_DELIVERY_DESC: "Orders are processed automatically and start running within minutes of checkout.",
    FEAT_SUPPORT_TITLE: "24/7 Customer Support",
    FEAT_SUPPORT_DESC: "Our expert support staff is always online to solve order and payment issues.",
    FEAT_PRICING_TITLE: "Unbeatable Prices",
    FEAT_PRICING_DESC: "Direct supplier rates. Get premium quality services for a fraction of standard costs.",
    FEAT_SECURE_TITLE: "Secure Payment Methods",
    FEAT_SECURE_DESC: "Multiple verified payment methods to keep your financial transactions safe.",
    FEAT_REFILL_TITLE: "Refill Guarantee",
    FEAT_REFILL_DESC: "Selected services offer a free 30-day drop refill guarantee for absolute peace of mind.",
    FEAT_API_TITLE: "Fully Documented API",
    FEAT_API_DESC: "Integrate our high-speed services directly into your own reselling store via JSON API.",
    TESTIMONIALS_TITLE: "What Our Clients Say",
    TESTIMONIALS_SUBTITLE: "Trusted by thousands of agencies, influencers, and resellers globally",
    FAQ_TITLE: "Frequently Asked Questions",
    FAQ_SUBTITLE: "Find answers to general questions about our Virtue services",
    FOOTER_TEXT: "The world's leading social media marketing platform. Providing high quality and cheap services for resellers and individuals since 2026.",
    FOOTER_LINKS_TITLE: "Quick Links",
    FOOTER_SUPPORT_TITLE: "Help & Support",
  },
  AUTH: {
    LOGIN_TITLE: "Sign In",
    LOGIN_SUBTITLE: "Access your dashboard and place orders",
    REGISTER_TITLE: "Sign Up",
    REGISTER_SUBTITLE: "Create a free account to begin your growth journey",
    FORGOT_PASSWORD_TITLE: "Forgot Password?",
    FORGOT_PASSWORD_SUBTITLE: "Enter your email address and we'll send a password reset link",
    RESET_PASSWORD_TITLE: "Reset Password",
    RESET_PASSWORD_SUBTITLE: "Choose a strong new password for your account",
    VERIFY_EMAIL_TITLE: "Verify Your Email",
    VERIFY_EMAIL_SUBTITLE: "Confirming your email verification token...",
    EMAIL_LABEL: "Email Address",
    USERNAME_LABEL: "Username",
    PASSWORD_LABEL: "Password",
    CONFIRM_PASSWORD_LABEL: "Confirm Password",
    FULL_NAME_LABEL: "Full Name",
    REFERRAL_CODE_LABEL: "Referral Code (Optional)",
    REMEMBER_ME: "Remember Me",
    TERMS_AGREE: "I agree to the Terms & Conditions and Privacy Policy",
    FORGOT_PASSWORD_LINK: "Forgot Password?",
    NO_ACCOUNT: "Don't have an account?",
    HAVE_ACCOUNT: "Already have an account?",
    BACK_TO_LOGIN: "Back to Login",
    SEND_RESET_LINK: "Send Reset Link",
    UPDATE_PASSWORD: "Update Password",
    GOOGLE_OAUTH: "Continue with Google",
    REGISTER_BTN: "Register",
    LOGIN_BTN: "Sign In",
    EMAIL_PLACEHOLDER: "name@example.com",
    USERNAME_PLACEHOLDER: "johndoe",
    PASSWORD_PLACEHOLDER: "••••••••",
    FULL_NAME_PLACEHOLDER: "John Doe",
    REFERRAL_PLACEHOLDER: "REF12345",
  },
  DASHBOARD: {
    TITLE: "User Dashboard",
    NAV_DASHBOARD: "Dashboard",
    NAV_NEW_ORDER: "New Order",
    NAV_ORDERS: "My Orders",
    NAV_SERVICES: "Services List",
    NAV_ADD_FUNDS: "Add Funds",
    NAV_TRANSACTIONS: "Transactions",
    NAV_PROFILE: "My Profile",
    NAV_SUPPORT: "Support Tickets",
    NAV_API: "API Docs",
    NAV_AFFILIATE: "Affiliate System",
    NAV_CONTACT: "Contact Us",
    NAV_LOGOUT: "Logout",
    NAV_ADMIN: "Admin Panel",
    WALLET_BALANCE: "Wallet Balance",
    NOTIFICATION_BELL: "Notifications",
    STATS_BALANCE: "Wallet Balance",
    STATS_TOTAL_ORDERS: "Total Orders",
    STATS_PENDING: "Pending",
    STATS_COMPLETED: "Completed",
    STATS_IN_PROGRESS: "In Progress",
    QUICK_ORDER_TITLE: "Quick Order Placement",
    RECENT_ORDERS_TITLE: "Recent Orders",
    RECENT_TRANSACTIONS_TITLE: "Recent Transactions",
    SHORTCUTS_TITLE: "Platform Shortcuts",
    ORDER_CONFIRM_TITLE: "Confirm Your Order",
    NEW_ORDER_TITLE: "Place A New Order",
    SERVICE_DETAILS: "Service Specifications",
    TARGET_URL_LABEL: "Target Link / URL / Username",
    TARGET_URL_PLACEHOLDER: "https://www.instagram.com/p/abc123xyz",
    QUANTITY_LABEL: "Order Quantity",
    QUANTITY_PLACEHOLDER: "Min: {min} - Max: {max}",
    PRICE_PREVIEW_LABEL: "Total Price (Estimated)",
    PLACE_ORDER_BTN: "Place Order Now",
    ORDER_SUCCESS_MSG: "Order placed successfully! Order ID: {id}",
    ADD_FUNDS_TITLE: "Add Funds to Wallet",
    ADD_FUNDS_DESC: "Deposit money to your wallet instantly using secure options.",
    METHOD_SELECT_LABEL: "Select Deposit Method",
    AMOUNT_LABEL: "Enter Amount (INR)",
    AMOUNT_PLACEHOLDER: "Enter custom amount in ₹",
    PAY_NOW_BTN: "Deposit & Pay Now",
    PENDING_PAYMENTS_TITLE: "Recent Payments Log",
    TRANSACTIONS_TITLE: "Transaction Ledger",
    TRANSACTIONS_FILTER_ALL: "All Actions",
    TRANSACTIONS_FILTER_CREDIT: "Credits (Deposits)",
    TRANSACTIONS_FILTER_DEBIT: "Debits (Orders)",
    DATE_RANGE_LABEL: "Filter Date Range",
    PROFILE_TITLE: "Profile & Security Settings",
    PROFILE_TAB_INFO: "Personal Information",
    PROFILE_TAB_SECURITY: "Security & Sessions",
    PROFILE_TAB_API: "Developer API Settings",
    PROFILE_TAB_NOTIFICATIONS: "Notifications",
    ACTIVE_SESSIONS: "Active Logged-in Sessions",
    LOGOUT_ALL_DEVICES: "Sign Out From All Other Devices",
    API_KEY_TITLE: "Your Developer API Credentials",
    API_KEY_DESC: "Use this key to automate orders through your own reseller application.",
    REGENERATE_BTN: "Regenerate API Key",
    COPY_BTN: "Copy Key",
    NOTIF_SETTINGS_TITLE: "Notification Preferences",
    SUPPORT_TITLE: "Customer Support & Tickets",
    CREATE_TICKET_TITLE: "Open a Support Ticket",
    TICKET_SUBJECT_LABEL: "Ticket Subject",
    TICKET_SUBJECT_PLACEHOLDER: "e.g., Order ID #10243 not started",
    TICKET_CAT_LABEL: "Select Issue Category",
    TICKET_MESSAGE_LABEL: "Detailed Description",
    TICKET_MESSAGE_PLACEHOLDER: "Describe your query or order problem in detail...",
    TICKET_FILE_LABEL: "Attach Screenshot (Optional)",
    SUBMIT_TICKET_BTN: "Create Ticket",
    TICKET_LIST_TITLE: "Your Tickets History",
    TICKET_THREAD_TITLE: "Ticket #{id} - {subject}",
    TICKET_REPLY_PLACEHOLDER: "Write your message response here...",
    TICKET_REPLY_BTN: "Send Reply",
    CLOSE_TICKET_BTN: "Close Support Ticket",
    API_DOCS_TITLE: "Reseller API Documentation",
    API_DOCS_DESC: "Integrate Virtue directly with your systems. All requests are formatted in JSON.",
    AFFILIATE_TITLE: "Affiliate & Referral Program",
    AFFILIATE_DESC: "Share your referral link and earn a 5% commission on every fund deposit made by your referrals!",
    REFERRAL_LINK_LABEL: "Your Custom Referral Link",
    AFFILIATE_STATS_REFERRED: "Total Referred Users",
    AFFILIATE_STATS_EARNED: "Total Commission Earned",
    AFFILIATE_STATS_PENDING: "Withdrawable Commission",
    WITHDRAW_COMMISSION_BTN: "Withdraw Commission to Wallet",
  },
  ADMIN: {
    TITLE: "Admin Control Panel",
    NAV_ADMIN_DASHBOARD: "Admin Home",
    NAV_MANAGE_USERS: "Users Management",
    NAV_MANAGE_ORDERS: "Orders Management",
    NAV_MANAGE_SERVICES: "Services Catalog",
    NAV_MANAGE_CATEGORIES: "Categories Catalog",
    NAV_MANAGE_PAYMENTS: "Payments & Ledger",
    NAV_MANAGE_TICKETS: "Support Tickets Hub",
    NAV_CONTACT_REQUESTS: "Contact Requests",
    NAV_SETTINGS: "Website Settings",
    NAV_SITE_SETTINGS: "Website Settings",
    STATS_TOTAL_USERS: "Total Registered Users",
    STATS_REVENUE_TODAY: "Revenue Today",
    STATS_ORDERS_TODAY: "Orders Placed Today",
    STATS_OPEN_TICKETS: "Open Support Tickets",
    STATS_ACTIVE_SERVICES: "Active Panel Services",
    REVENUE_CHART_TITLE: "Financial Performance (Last 30 Days)",
    ORDER_STATUS_DONUT_TITLE: "Orders Status Share",
    RECENT_REGISTRATIONS_TITLE: "Recent Registrations",
    EDIT_BALANCE_TITLE: "Adjust Wallet Balance",
    USER_DETAILS_TITLE: "User details for {username}",
    IMPERSONATE_USER_BTN: "Impersonate",
    BAN_USER_BTN: "Ban Account",
    UNBAN_USER_BTN: "Remove Ban",
    BULK_ACTIONS_LABEL: "Bulk Update Selected Orders",
    IMPORT_SERVICES_TITLE: "Import Services from Provider",
    SITE_SETTINGS_TITLE: "Global System Settings",
    SETTING_SITE_NAME: "Platform Site Name",
    SETTING_TAGLINE: "Marketing Tagline",
    SETTING_EMAIL: "Support Email Address",
    SETTING_WHATSAPP: "WhatsApp Support Link",
    SETTING_MAINTENANCE: "Activate Maintenance Mode",
    SETTING_REGISTRATION: "Open Registrations to Public",
    SETTING_MIN_ORDER: "Minimum Order Amount (₹)",
    SETTING_BANNER: "Announcement Banner Text",
    SETTING_THRESHOLD: "Low Balance Threshold Notification",
  },
  VALIDATION: {
    REQUIRED: "This field is mandatory.",
    EMAIL_INVALID: "Please enter a valid email address.",
    USERNAME_INVALID: "Username must be at least 4 characters long and contain alphanumeric characters only.",
    PASSWORD_SHORT: "Password must be at least 8 characters long.",
    PASSWORD_STRENGTH: "Password must contain a letter, a number, and a special character.",
    PASSWORD_MISMATCH: "Passwords do not match.",
    TERMS_REQUIRED: "You must accept our Terms and Conditions to proceed.",
    AMOUNT_MIN: "Deposit amount must be at least ₹100.",
    AMOUNT_MAX: "Deposit amount cannot exceed ₹50,000.",
    QUANTITY_MIN: "Quantity must be at least {min} for this service.",
    QUANTITY_MAX: "Quantity cannot exceed {max} for this service.",
    URL_INVALID: "Please enter a valid social link URL.",
  },
  COMMON: {
    LOAD_MORE: "Load More",
    LOADING: "Processing...",
    SUBMIT: "Submit",
    CANCEL: "Cancel",
    DELETE: "Delete",
    EDIT: "Edit",
    VIEW: "View Details",
    REFRESH: "Refresh",
    SEARCH_PLACEHOLDER: "Search elements...",
    NO_DATA: "No items found.",
    PREVIOUS: "Prev",
    NEXT: "Next",
    STATUS_PENDING: "Pending",
    STATUS_IN_PROGRESS: "In Progress",
    STATUS_COMPLETED: "Completed",
    STATUS_CANCELLED: "Cancelled",
    STATUS_PARTIAL: "Partial",
    STATUS_REFUNDED: "Refunded",
  },
} as const;
